language: java
sudo: false
jdk:
  - oraclejdk8
dist: trusty
addons:
  chrome: stable
before_install:
  - chmod +x ./gradle/buildViaTravis.sh
  - test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_e795b1861862_key -iv $encrypted_e795b1861862_iv -in gradle.properties.enc -out gradle.properties -d || true
install:
  - wget 'https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip'
  - sudo apt-get install -y unzip
  - mkdir -p $TRAVIS_BUILD_DIR/drivers
  - unzip chromedriver_linux64.zip -d $TRAVIS_BUILD_DIR/drivers
  - wget 'https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz'
  - tar xzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo mv geckodriver $TRAVIS_BUILD_DIR/drivers
  - PATH=$PATH:$TRAVIS_BUILD_DIR/drivers
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: ./gradle/buildViaTravis.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
  - ./gradlew jacocoTestReport coveralls